### PR TITLE
RA-1955:Updating Reference Application Diagnoses concepts

### PR DESCRIPTION
**Pull request by HerbertYiga**
Updating Reference Application Diagnoses concepts

Ticket Id
https://issues.openmrs.org/browse/RA-1955

### CODE REVIEW

**Comment by HerbertYiga** [comment]
cc @dkayiwa  @sherrif10

**Comment by HerbertYiga** [comment]
hi @dkayiwa  does this look good enough to be merged in?

**Comment by HerbertYiga** [comment]
could it be clear enough now

**Comment by tendomart** [comment]
@HerbertYiga  nga you're missing the link to the Ticket ,or i just missed out to see it.

**Pull request merged**
