### PR TITLE
RA-1170: replaced retired_by=1 by retired_by=null

### PR DESCRIPTION
**Pull request by piyush9620**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@piyush9620 can you take a look at the above travis failure?

**Comment by dkayiwa** [comment]
@piyush9620 did you get a chance to look at the travis failure?

**Comment by piyush9620** [comment]
Yes I had a look at it, it has many(a lot) typecasting errors like cannot convert null to Integer.

**Comment by dkayiwa** [comment]
So are you fixing them? :)

**Comment by piyush9620** [comment]
can you please have a look at the travis failure, there are a lot of these errors, what do you suggest?

**Comment by dkayiwa** [comment]
just run mvn clean install locally and you will see the test failures

**Comment by dkayiwa** [comment]
@piyush9620 are you still working on this?

**Comment by dkayiwa** [comment]
@piyush9620 ping me to reopen this when you are back. :)

**Pull request closed without merging**
