### PR TITLE
RA-1170: retired_by concepts removed from 3 .xml files

### PR DESCRIPTION
**Pull request by iranganN**
the commits in previous pull requests are combined

### CODE REVIEW

**Comment by iranganN** [comment]
https://issues.openmrs.org/browse/RA-1170
@dkayiwa

**Comment by dkayiwa** [comment]
@iranganN despite the changes you have made, i still see a number of records with retired_by="1" where retired = "false"

**Comment by dkayiwa** [comment]
@iranganN are you still working on this?

**Comment by dkayiwa** [comment]
@iranganN i can reopen this when you resume working on it.

**Pull request closed without merging**
