### PR TITLE
I removed retired_by=1 where retire=false

### PR DESCRIPTION
**Pull request by samuelmale**
Issue : https://issues.openmrs.org/browse/RA-1170
Details : I removed retired_by=1 where retire=false

### CODE REVIEW

**Comment by dkayiwa** [comment]
The commit message should always include the ticket number

**Comment by samuelmale** [comment]
Thanks for that resource. Am sorry for not following the convention @dkayiwa

**Comment by dkayiwa** [comment]
I have seen some rows with retired_by="1" but without retired="true"

**Comment by samuelmale** [comment]
@dkayiwa  Let me do more checking for those fields. I thought I had cleared everything.

**Comment by samuelmale** [comment]
@dkayiwa  This time round am sure everything is cleaned up. I have checked thoroughly!

**Pull request merged**
