### PR TITLE
RA-1170: removed the retired_by value for Reference App Metadata concepts where retired = "false"

### PR DESCRIPTION
**Pull request by iranganN**
The retired_by = 1 values were removed from 3 .xml files in openmrs-module-referencemetadata/api/src/main/resources. listed below are these .xml files.
Reference_Application_Concepts-21
Reference_Application_Diagnoses-9
Reference_Application_Order_Entry_and_Allergies_Concepts-16

### CODE REVIEW

**Comment by dkayiwa** [comment]
You seem to have committed more than just those three files. Can you look into it?

**Comment by iranganN** [comment]
16 files are committed. However, only 3 of them have changes. Other files have no changes. Is it going to be a problem? Please let me know.

**Comment by dkayiwa** [comment]
Can you do it again and ensure that you do not commit files that you did not change?

**Comment by iranganN** [comment]
Do you want me to close this pull request and open a new one?

**Comment by dkayiwa** [comment]
Whichever you find easier.

**Pull request closed without merging**
